### ISSUE TITLE
TypeError, pip install fails

### ISSUE THREAD

**Issue by HWDexperte** [jazzband/django-dbtemplates#73]
I'm using `python 3.4.1` together with `django 1.9.4` and while i'm executing the following command

```bash
pip install django-dbtemplates
```

i get this weird error message:

```bash
Collecting django-dbtemplates
  Using cached django-dbtemplates-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j7vzt90r/django-dbtemplates/setup.py", line 22, in <module>
        version=find_version('dbtemplates', '__init__.py'),
      File "/tmp/pip-build-j7vzt90r/django-dbtemplates/setup.py", line 14, in find_version
        version_file, re.M)
      File "/home/fechnert/projects/salt-observer/env/lib64/python3.4/re.py", line 166, in search
        return _compile(pattern, flags).search(string)
    TypeError: can't use a string pattern on a bytes-like object
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j7vzt90r/django-dbtemplates/
```

Can someone of you help me out?

**Comment by jezdez** [comment]
@HWDexperte django-dbtemplates hasn't been ported to Python 3 yet
